### ISSUE TITLE
Loan 2889 cannot be loaded

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/INHS-Insect-Collection-Data-Curation#19]
Might be linked to cross-OTUs/determinations?
https://sfg.taxonworks.org/loans/1513

**Comment by tmcelrath** [comment]
mmmh, I guess this exception comes from that:

https://github.com/SpeciesFileGroup/taxonworks/blob/11a7df9e6/app/models/loan_item.rb#L94
```
An ActionView::Template::Error occurred in loans#show:

  undefined method `total' for nil:NilClass
  app/models/loan_item.rb:94:in `total_items'


-------------------------------
Github link:
-------------------------------

  https://github.com/SpeciesFileGroup/taxonworks/blob/11a7df9e6/app/models/loan_item.rb#L94

-------------------------------
Request:
-------------------------------

  * URL        : https://sfg.taxonworks.org/loans/1513
  * HTTP Method: GET
  * IP address : 10.32.0.1
  * Parameters : {"controller"=>"loans", "action"=>"show", "id"=>"1513"}
  * Timestamp  : 2020-12-02 19:34:55 UTC
  * Server : taxonworks-565f7dccf5-wjtgl
    * Rails root : /app
  * Process: 2156

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"d76b36d605d5c68f1d22d93972125e68",
   "_csrf_token"=>"/gSXivPenk0IVHBM1xWvz5ETfi44zEkn8l/hiVYMgeY=",
   "project_id"=>1}

-------------------------------
Environment:
-------------------------------

  * HTTP_ACCEPT                                             : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
    * HTTP_ACCEPT_ENCODING                                    : gzip, deflate, br
    * HTTP_ACCEPT_LANGUAGE                                    : en-US,en;q=0.9,es;q=0.8
    * HTTP_COOKIE                                             : remember_token=ttuOtJsChYY87EACZSIzPA; _TaxonWorks_session=MGRFaFNZdEg1aEkraFYxZDNMNHlReS9kWElwamRFMENKc0E1UGNBVEp5ZnNBQVlqZGxWL3lLb09tdnVtOTlhSE50REd2MkthTmNvbnVUZzdDN0V5aFBVUkpvQ0lpK1BDWXJsNU5yOTB2M3RNZkU2TTJvc2k4cTVwRDdQdDJ1aVBhc2t0UksyelpvYllnbktiOE1sZUVEZFNjM2E2Wms0SjB2R3p4cnZTeUxDQXhzUElBOUxlZFRYOCtrOG9wY2h2ZGs3ZXc2dzd2N0J3UTBLUUQxb3U1TTU5bUlhMDZ5NGlEeFIvbTVlWXpxNEdwWEwwS3dQTEtEOE9ERVRaOGRzNVhCVHd6dFc4Y2l5S21FcEVHV1FTclZlTUp2ZGtCVHl2Tlc1K2ZsMURhV00xZUdLMUlFdjN3bnlSZ0xjdXo5S3lMWkw0OGRnTHZ6NVJZbWMzOVpCYWVpVDdDWEcxY3g4N2FKcWNDdlhiS1ZrPS0tblc2bkNORytOb2RRVmNRR1k3bGVIQT09--c1b8a04236d432d36e4190217a7855493d7e8668
    * HTTP_DNT                                                : 1
    * HTTP_HOST                                               : sfg.taxonworks.org
    * HTTP_REFERER                                            : https://sfg.taxonworks.org/loans/1512
    * HTTP_SEC_FETCH_DEST                                     : document
    * HTTP_SEC_FETCH_MODE                                     : navigate
    * HTTP_SEC_FETCH_SITE                                     : same-origin
    * HTTP_SEC_FETCH_USER                                     : ?1
    * HTTP_UPGRADE_INSECURE_REQUESTS                          : 1
    * HTTP_USER_AGENT                                         : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36
    * HTTP_VERSION                                            : HTTP/1.1
    * HTTP_X_FORWARDED_FOR                                    : 10.251.55.58, 127.0.0.1
    * HTTP_X_FORWARDED_PORT                                   : 443
    * HTTP_X_FORWARDED_PROTO                                  : https
    * HTTP_X_REAL_IP                                          : 10.251.55.58
    * HTTP_X_VARNISH                                          : 1226707
    * ORIGINAL_FULLPATH                                       : /loans/1513
    * ORIGINAL_SCRIPT_NAME                                    :
    * PASSENGER_CONNECT_PASSWORD                              : [FILTERED]
    * PATH_INFO                                               : /loans/1513
    * QUERY_STRING                                            :
    * REMOTE_ADDR                                             : 10.32.0.1
    * REMOTE_PORT                                             : 46446
    * REQUEST_METHOD                                          : GET
    * REQUEST_URI                                             : /loans/1513
    * ROUTES_66960_SCRIPT_NAME                                :
    * SCRIPT_NAME                                             :
    * SERVER_NAME                                             : sfg.taxonworks.org
    * SERVER_PORT                                             : 80
    * SERVER_PROTOCOL                                         : HTTP/1.1
    * SERVER_SOFTWARE                                         : nginx/1.18.0 Phusion_Passenger/6.0.7
    * action_controller.instance                              : #<LoansController:0x00007f1702238ff0>
    * action_dispatch.authenticated_encrypted_cookie_salt     : authenticated encrypted cookie
    * action_dispatch.backtrace_cleaner                       : #<Rails::BacktraceCleaner:0x000055e72ac083b8>
    * action_dispatch.content_security_policy                 :
    * action_dispatch.content_security_policy_nonce_directives:
    * action_dispatch.content_security_policy_nonce_generator :
    * action_dispatch.content_security_policy_report_only     : false
    * action_dispatch.cookies                                 : #<ActionDispatch::Cookies::CookieJar:0x00007f170223dff0>
    * action_dispatch.cookies_digest                          :
    * action_dispatch.cookies_rotations                       : #<ActiveSupport::Messages::RotationConfiguration:0x000055e726bba450>
    * action_dispatch.cookies_serializer                      :
    * action_dispatch.encrypted_cookie_cipher                 :
    * action_dispatch.encrypted_cookie_salt                   : encrypted cookie
    * action_dispatch.encrypted_signed_cookie_salt            : signed encrypted cookie
    * action_dispatch.http_auth_salt                          : http authentication
    * action_dispatch.key_generator                           : #<ActiveSupport::CachingKeyGenerator:0x000055e730d09a40>
    * action_dispatch.logger                                  : #<ActiveSupport::Logger:0x000055e72be34c80>
    * action_dispatch.parameter_filter                        : [:password, :password_confirmation]
    * action_dispatch.redirect_filter                         : []
    * action_dispatch.remote_ip                               : 10.32.0.1
    * action_dispatch.request.content_type                    :
    * action_dispatch.request.formats                         : [#<Mime::Type:0x000055e7284917d0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-1300675627797050692>]
    * action_dispatch.request.parameters                      : {"controller"=>"loans", "action"=>"show", "id"=>"1513"}
    * action_dispatch.request.path_parameters                 : {:controller=>"loans", :action=>"show", :id=>"1513"}
    * action_dispatch.request.query_parameters                : {}
    * action_dispatch.request.request_parameters              : {}
    * action_dispatch.request.unsigned_session_cookie         : {"session_id"=>"d76b36d605d5c68f1d22d93972125e68", "_csrf_token"=>"/gSXivPenk0IVHBM1xWvz5ETfi44zEkn8l/hiVYMgeY=", "project_id"=>1}
    * action_dispatch.request_id                              : cc408547-8d9e-490b-9cb9-4016d8d7d161
    * action_dispatch.routes                                  : #<ActionDispatch::Routing::RouteSet:0x000055e72bf6c2d8>
    * action_dispatch.secret_key_base                         : 5a3620de96056199af7ef47fe8065d38eee932137a0a7465c641744b150ea32ed5da5a658639edd91bf419a91a376a6b02eddca2c4cbf860b15a7cbe68a4e66e
    * action_dispatch.show_detailed_exceptions                : false
    * action_dispatch.show_exceptions                         : true
    * action_dispatch.signed_cookie_digest                    :
    * action_dispatch.signed_cookie_salt                      : signed cookie
    * action_dispatch.use_authenticated_cookie_encryption     : false
    * action_dispatch.use_cookies_with_metadata               : false
    * exception_notifier.exception_data                       : {:user=>{:user_id=>51, :user_email=>"mmkohler@illinois.edu"}, :project=>{:project_id=>1, :project_name=>"INHS Insect Collection"}}
    * rack.cors                                               : #<Rack::Cors::Result:0x00007f1702231110>
    * rack.errors                                             : #<IO:0x000055e7268d3778>
    * rack.hijack                                             : #<Proc:0x00007f17022313b8 /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94 (lambda)>
    * rack.hijack?                                            : true
    * rack.input                                              : #<PhusionPassenger::Utils::TeeInput:0x00007f17022315e8>
    * rack.multiprocess                                       : true
    * rack.multithread                                        : false
    * rack.request.cookie_hash                                : {"remember_token"=>"ttuOtJsChYY87EACZSIzPA", "_TaxonWorks_session"=>"MGRFaFNZdEg1aEkraFYxZDNMNHlReS9kWElwamRFMENKc0E1UGNBVEp5ZnNBQVlqZGxWL3lLb09tdnVtOTlhSE50REd2MkthTmNvbnVUZzdDN0V5aFBVUkpvQ0lpK1BDWXJsNU5yOTB2M3RNZkU2TTJvc2k4cTVwRDdQdDJ1aVBhc2t0UksyelpvYllnbktiOE1sZUVEZFNjM2E2Wms0SjB2R3p4cnZTeUxDQXh...
    * rack.request.cookie_string                              : remember_token=ttuOtJsChYY87EACZSIzPA; _TaxonWorks_session=MGRFaFNZdEg1aEkraFYxZDNMNHlReS9kWElwamRFMENKc0E1UGNBVEp5ZnNBQVlqZGxWL3lLb09tdnVtOTlhSE50REd2MkthTmNvbnVUZzdDN0V5aFBVUkpvQ0lpK1BDWXJsNU5yOTB2M3RNZkU2TTJvc2k4cTVwRDdQdDJ1aVBhc2t0UksyelpvYllnbktiOE1sZUVEZFNjM2E2Wms0SjB2R3p4cnZTeUxDQXhzUElBOUxlZFRYOCtrOG9wY2h2ZGs3ZXc2dzd2N0J3UTBLUUQxb3U1TTU5bUlhMDZ5NGlEeFIvbTVlWXpxNEdwWEwwS3dQTEtEOE9ERVRaOGRzNVhCVHd6dFc4Y2l5S21FcEVHV1FTclZlTUp2ZGtCVHl2Tlc1K2ZsMURhV00xZUdLMUlFdjN3bnlSZ0xjdXo5S3lMWkw0OGRnTHZ6NVJZbWMzOVpCYWVpVDdDWEcxY3g4N2FKcWNDdlhiS1ZrPS0tblc2bkNORytOb2RRVmNRR1k3bGVIQT09--c1b8a04236d432d36e4190217a7855493d7e8668
    * rack.request.query_hash                                 : {}
    * rack.request.query_string                               :
    * rack.run_once                                           : false
    * rack.session                                            : #<ActionDispatch::Request::Session:0x00007f1702234fb8>
    * rack.session.options                                    : #<ActionDispatch::Request::Session::Options:0x00007f1702234f68>
    * rack.tempfiles                                          : []
    * rack.url_scheme                                         : http
    * rack.version                                            : [1, 2]

-------------------------------
Backtrace:
-------------------------------

  app/models/loan_item.rb:94:in `total_items'
  app/helpers/loan_items_helper.rb:24:in `loan_item_total_string'
  app/views/loan_items/_loan_table.erb:13
  app/views/loan_items/_loan_table.erb:10
  app/views/loan_items/_loan_table.erb:9
  app/views/loans/show.html.erb:41
  app/views/loans/show.html.erb:14

-------------------------------
Full backtrace:
-------------------------------

  /app/app/models/loan_item.rb:94:in `total_items'
  /app/app/helpers/loan_items_helper.rb:24:in `loan_item_total_string'
  /app/app/views/loan_items/_loan_table.erb:13:in `block (2 levels) in _app_views_loan_items__loan_table_erb___469004590971437076_332800'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/capture_helper.rb:45:in `capture'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/tag_helper.rb:273:in `content_tag'
  /app/app/views/loan_items/_loan_table.erb:10:in `block in _app_views_loan_items__loan_table_erb___469004590971437076_332800'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.3/lib/active_record/relation/delegation.rb:87:in `each'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.3/lib/active_record/relation/delegation.rb:87:in `each'
  /app/app/views/loan_items/_loan_table.erb:9:in `_app_views_loan_items__loan_table_erb___469004590971437076_332800'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/base.rb:274:in `_run'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/template.rb:185:in `block in render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:182:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/template.rb:385:in `instrument_render_template'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/template.rb:183:in `render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/partial_renderer.rb:346:in `render_partial'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/partial_renderer.rb:317:in `render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/renderer.rb:53:in `render_partial'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/rendering_helper.rb:38:in `render'
  /app/app/views/loans/show.html.erb:41:in `block in _app_views_loans_show_html_erb__2759957391473733664_332780'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/capture_helper.rb:45:in `capture'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/helpers/capture_helper.rb:159:in `content_for'
  /app/app/views/loans/show.html.erb:14:in `_app_views_loans_show_html_erb__2759957391473733664_332780'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/base.rb:274:in `_run'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/template.rb:185:in `block in render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:182:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/template.rb:385:in `instrument_render_template'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/template.rb:183:in `render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/template_renderer.rb:56:in `render_template'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/template_renderer.rb:13:in `render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:117:in `block in _render_template'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/base.rb:304:in `in_rendering_context'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:116:in `_render_template'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/streaming.rb:218:in `_render_template'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:103:in `render_to_body'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/abstract_controller/rendering.rb:25:in `render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/rendering.rb:36:in `render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/core_ext/benchmark.rb:14:in `ms'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.3/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:195:in `process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:135:in `run_callbacks'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:136:in `process'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:39:in `process'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:190:in `dispatch'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:254:in `dispatch'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:49:in `block in serve'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `each'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `serve'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:834:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/exception_notification-4.4.3/lib/exception_notification/rack.rb:49:in `call'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/cookies.rb:648:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:101:in `run_callbacks'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:37:in `call_app'
  /usr/local/rvm/gems/ruby-2.7.2/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `block in call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `block in tagged'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:28:in `tagged'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `tagged'
  /usr/local/rvm/gems/ruby-2.7.2/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/static.rb:126:in `call'
  /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
  /usr/local/rvm/gems/ruby-2.7.2/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

-------------------------------
Data:
-------------------------------

  * data: {:user=>{:user_id=>51, :user_email=>"mmkohler@illinois.edu"},
   :project=>{:project_id=>1, :project_name=>"INHS Insect Collection"}}

```

**Comment by tmcelrath** [comment]
Fixed.
